default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: tests
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
        exclude: tests/fixtures/invalid_lock/uv\.lock
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --respect-gitignore]
        exclude: ".*uv.lock|.*_static"
      # Run the formatter.
      - id: ruff-format
        args: [--respect-gitignore]
        exclude: ".*uv.lock|.*_static"
  # Inspired by: https://medium.com/@fistralpro/pytest-pre-commit-hook-b492edd0560e
  # Running pytest with uv will slow down the commit process.
  # - repo: local
  #   hooks:
  #   - id: pytest
  #     name: pytest using uv
  #     entry: sh -c "uv run --group test pytest tests/"
  #     language: system
  #     types: [python]
  #     pass_filenames: false
  #     always_run: true
